export interface Database {
  public: {
    Tables: {
      menus: {
        Row: {
          id: string;
          parent_id: string | null;
          page_id: string | null;
          title: string;
          slug: string;
          route: string | null;
          icon: string | null;
          description: string | null;
          audience: string;
          status: string;
          visibility: boolean;
          sort_order: number;
          permission: string;
          metadata: Record<string, unknown> | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          parent_id?: string | null;
          page_id?: string | null;
          title: string;
          slug: string;
          route?: string | null;
          icon?: string | null;
          description?: string | null;
          audience?: string;
          status?: string;
          visibility?: boolean;
          sort_order?: number;
          permission?: string;
          metadata?: Record<string, unknown> | null;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          parent_id?: string | null;
          page_id?: string | null;
          title?: string;
          slug?: string;
          route?: string | null;
          icon?: string | null;
          description?: string | null;
          audience?: string;
          status?: string;
          visibility?: boolean;
          sort_order?: number;
          permission?: string;
          metadata?: Record<string, unknown> | null;
          created_by?: string | null;
        };
      };
      pages: {
        Row: {
          id: string;
          title: string;
          slug: string;
          subtitle: string | null;
          description: string | null;
          icon: string | null;
          layout_type: string;
          seo_title: string | null;
          seo_description: string | null;
          status: string;
          visibility: boolean;
          sort_order: number;
          metadata: Record<string, unknown> | null;
          published_at: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          subtitle?: string | null;
          description?: string | null;
          icon?: string | null;
          layout_type?: string;
          seo_title?: string | null;
          seo_description?: string | null;
          status?: string;
          visibility?: boolean;
          sort_order?: number;
          metadata?: Record<string, unknown> | null;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          subtitle?: string | null;
          description?: string | null;
          icon?: string | null;
          layout_type?: string;
          seo_title?: string | null;
          seo_description?: string | null;
          status?: string;
          visibility?: boolean;
          sort_order?: number;
          metadata?: Record<string, unknown> | null;
        };
      };
      sections: {
        Row: {
          id: string;
          page_id: string;
          section_type: string;
          title: string;
          subtitle: string | null;
          description: string | null;
          icon: string | null;
          layout_type: string;
          content_json: Record<string, unknown> | null;
          metadata: Record<string, unknown> | null;
          sort_order: number;
          visibility: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          page_id: string;
          section_type?: string;
          title: string;
          subtitle?: string | null;
          description?: string | null;
          icon?: string | null;
          layout_type?: string;
          content_json?: Record<string, unknown> | null;
          metadata?: Record<string, unknown> | null;
          sort_order?: number;
          visibility?: boolean;
        };
        Update: {
          id?: string;
          page_id?: string;
          section_type?: string;
          title?: string;
          subtitle?: string | null;
          description?: string | null;
          icon?: string | null;
          layout_type?: string;
          content_json?: Record<string, unknown> | null;
          metadata?: Record<string, unknown> | null;
          sort_order?: number;
          visibility?: boolean;
        };
      };
      architecture_diagrams: {
        Row: {
          id: string;
          section_id: string | null;
          title: string;
          slug: string | null;
          architecture_type: string;
          description: string | null;
          icon: string | null;
          layout_type: string;
          background: string | null;
          nodes: unknown[] | null;
          connections: unknown[] | null;
          metadata: Record<string, unknown> | null;
          sort_order: number;
          visibility: boolean;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          section_id?: string | null;
          title: string;
          slug?: string | null;
          architecture_type?: string;
          description?: string | null;
          icon?: string | null;
          layout_type?: string;
          background?: string | null;
          nodes?: unknown[] | null;
          connections?: unknown[] | null;
          metadata?: Record<string, unknown> | null;
          sort_order?: number;
          visibility?: boolean;
        };
        Update: {
          id?: string;
          section_id?: string | null;
          title?: string;
          slug?: string | null;
          architecture_type?: string;
          description?: string | null;
          icon?: string | null;
          layout_type?: string;
          background?: string | null;
          nodes?: unknown[] | null;
          connections?: unknown[] | null;
          metadata?: Record<string, unknown> | null;
          sort_order?: number;
          visibility?: boolean;
        };
      };
      architecture_nodes: {
        Row: {
          id: string;
          diagram_id: string;
          title: string;
          subtitle: string | null;
          description: string | null;
          icon: string | null;
          node_type: string;
          position_x: number | null;
          position_y: number | null;
          sort_order: number;
          metadata: Record<string, unknown> | null;
          visibility: boolean;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          diagram_id: string;
          title: string;
          subtitle?: string | null;
          description?: string | null;
          icon?: string | null;
          node_type?: string;
          position_x?: number | null;
          position_y?: number | null;
          sort_order?: number;
          metadata?: Record<string, unknown> | null;
          visibility?: boolean;
        };
        Update: {
          id?: string;
          diagram_id?: string;
          title?: string;
          subtitle?: string | null;
          description?: string | null;
          icon?: string | null;
          node_type?: string;
          position_x?: number | null;
          position_y?: number | null;
          sort_order?: number;
          metadata?: Record<string, unknown> | null;
          visibility?: boolean;
        };
      };
      architecture_connections: {
        Row: {
          id: string;
          diagram_id: string;
          source_node_id: string;
          target_node_id: string;
          label: string | null;
          connection_type: string;
          direction: string;
          visibility: boolean;
          metadata: Record<string, unknown> | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          diagram_id: string;
          source_node_id: string;
          target_node_id: string;
          label?: string | null;
          connection_type?: string;
          direction?: string;
          visibility?: boolean;
          metadata?: Record<string, unknown> | null;
        };
        Update: {
          id?: string;
          diagram_id?: string;
          source_node_id?: string;
          target_node_id?: string;
          label?: string | null;
          connection_type?: string;
          direction?: string;
          visibility?: boolean;
          metadata?: Record<string, unknown> | null;
        };
      };
      settings: {
        Row: {
          id: string;
          key: string;
          value: unknown;
          description: string | null;
          category: string;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          value: unknown;
          description?: string | null;
          category?: string;
        };
        Update: {
          id?: string;
          key?: string;
          value?: unknown;
          description?: string | null;
          category?: string;
        };
      };
      files: {
        Row: {
          id: string;
          name: string;
          original_name: string;
          path: string;
          bucket: string;
          category: string;
          mime_type: string | null;
          size_bytes: number | null;
          width: number | null;
          height: number | null;
          alt_text: string | null;
          caption: string | null;
          metadata: Record<string, unknown> | null;
          uploaded_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          original_name: string;
          path: string;
          bucket?: string;
          category?: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          width?: number | null;
          height?: number | null;
          alt_text?: string | null;
          caption?: string | null;
          metadata?: Record<string, unknown> | null;
        };
        Update: {
          id?: string;
          name?: string;
          original_name?: string;
          path?: string;
          bucket?: string;
          category?: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          width?: number | null;
          height?: number | null;
          alt_text?: string | null;
          caption?: string | null;
          metadata?: Record<string, unknown> | null;
        };
      };
      downloads: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          file_url: string | null;
          file_name: string | null;
          file_type: string | null;
          file_size: number | null;
          version: string | null;
          category: string | null;
          platform: string | null;
          release_date: string | null;
          download_count: number | null;
          metadata: Record<string, unknown> | null;
          sort_order: number;
          visibility: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          file_url?: string | null;
          file_name?: string | null;
          file_type?: string | null;
          file_size?: number | null;
          version?: string | null;
          category?: string | null;
          platform?: string | null;
          release_date?: string | null;
          download_count?: number | null;
          metadata?: Record<string, unknown> | null;
          sort_order?: number;
          visibility?: boolean;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          file_url?: string | null;
          file_name?: string | null;
          file_type?: string | null;
          file_size?: number | null;
          version?: string | null;
          category?: string | null;
          platform?: string | null;
          release_date?: string | null;
          download_count?: number | null;
          metadata?: Record<string, unknown> | null;
          sort_order?: number;
          visibility?: boolean;
        };
      };
      environments: {
        Row: {
          id: string;
          name: string;
          type: string;
          backend_url: string | null;
          frontend_url: string | null;
          ssh_host: string | null;
          ssh_port: number | null;
          ssh_user: string | null;
          rds_host: string | null;
          rds_port: number | null;
          rds_database: string | null;
          rds_user: string | null;
          s3_bucket: string | null;
          s3_region: string | null;
          firebase_config: Record<string, unknown> | null;
          supabase_url: string | null;
          supabase_anon_key: string | null;
          metadata: Record<string, unknown> | null;
          sort_order: number;
          visibility: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type?: string;
          backend_url?: string | null;
          frontend_url?: string | null;
          ssh_host?: string | null;
          ssh_port?: number | null;
          ssh_user?: string | null;
          rds_host?: string | null;
          rds_port?: number | null;
          rds_database?: string | null;
          rds_user?: string | null;
          s3_bucket?: string | null;
          s3_region?: string | null;
          firebase_config?: Record<string, unknown> | null;
          supabase_url?: string | null;
          supabase_anon_key?: string | null;
          metadata?: Record<string, unknown> | null;
          sort_order?: number;
          visibility?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          type?: string;
          backend_url?: string | null;
          frontend_url?: string | null;
          ssh_host?: string | null;
          ssh_port?: number | null;
          ssh_user?: string | null;
          rds_host?: string | null;
          rds_port?: number | null;
          rds_database?: string | null;
          rds_user?: string | null;
          s3_bucket?: string | null;
          s3_region?: string | null;
          firebase_config?: Record<string, unknown> | null;
          supabase_url?: string | null;
          supabase_anon_key?: string | null;
          metadata?: Record<string, unknown> | null;
          sort_order?: number;
          visibility?: boolean;
        };
      };
      credentials: {
        Row: {
          id: string;
          label: string;
          encrypted_value: string | null;
          environment: string;
          category: string | null;
          visibility: string;
          description: string | null;
          metadata: Record<string, unknown> | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          label: string;
          encrypted_value?: string | null;
          environment?: string;
          category?: string | null;
          visibility?: string;
          description?: string | null;
          metadata?: Record<string, unknown> | null;
        };
        Update: {
          id?: string;
          label?: string;
          encrypted_value?: string | null;
          environment?: string;
          category?: string | null;
          visibility?: string;
          description?: string | null;
          metadata?: Record<string, unknown> | null;
        };
      };
      tasks: {
        Row: {
          id: string;
          milestone_id: string | null;
          title: string;
          module: string | null;
          description: string | null;
          assignee: string | null;
          status: string;
          priority: string;
          start_date: string | null;
          due_date: string | null;
          eta: string | null;
          progress_percent: number | null;
          version: string | null;
          sort_order: number;
          metadata: Record<string, unknown> | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          milestone_id?: string | null;
          title: string;
          module?: string | null;
          description?: string | null;
          assignee?: string | null;
          status?: string;
          priority?: string;
          start_date?: string | null;
          due_date?: string | null;
          eta?: string | null;
          progress_percent?: number | null;
          version?: string | null;
          sort_order?: number;
          metadata?: Record<string, unknown> | null;
        };
        Update: {
          id?: string;
          milestone_id?: string | null;
          title?: string;
          module?: string | null;
          description?: string | null;
          assignee?: string | null;
          status?: string;
          priority?: string;
          start_date?: string | null;
          due_date?: string | null;
          eta?: string | null;
          progress_percent?: number | null;
          version?: string | null;
          sort_order?: number;
          metadata?: Record<string, unknown> | null;
        };
      };
      milestones: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          status: string;
          start_date: string | null;
          due_date: string | null;
          sort_order: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          status?: string;
          start_date?: string | null;
          due_date?: string | null;
          sort_order?: number;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          status?: string;
          start_date?: string | null;
          due_date?: string | null;
          sort_order?: number;
        };
      };
      api_applications: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          icon: string | null;
          sort_order: number;
          visibility: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          icon?: string | null;
          sort_order?: number;
          visibility?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          icon?: string | null;
          sort_order?: number;
          visibility?: boolean;
        };
      };
      api_modules: {
        Row: {
          id: string;
          application_id: string | null;
          title: string;
          slug: string;
          description: string | null;
          icon: string | null;
          version: string;
          base_url: string | null;
          sort_order: number;
          visibility: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          application_id?: string | null;
          title: string;
          slug: string;
          description?: string | null;
          icon?: string | null;
          version?: string;
          base_url?: string | null;
          sort_order?: number;
          visibility?: boolean;
        };
        Update: {
          id?: string;
          application_id?: string | null;
          title?: string;
          slug?: string;
          description?: string | null;
          icon?: string | null;
          version?: string;
          base_url?: string | null;
          sort_order?: number;
          visibility?: boolean;
        };
      };
      api_endpoints: {
        Row: {
          id: string;
          module_id: string | null;
          title: string;
          method: string;
          endpoint: string;
          description: string | null;
          auth_requirement: string;
          tags: string[] | null;
          notes: string | null;
          version: string | null;
          deprecated: boolean;
          sort_order: number;
          visibility: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          module_id?: string | null;
          title: string;
          method?: string;
          endpoint: string;
          description?: string | null;
          auth_requirement?: string;
          tags?: string[] | null;
          notes?: string | null;
          version?: string | null;
          deprecated?: boolean;
          sort_order?: number;
          visibility?: boolean;
        };
        Update: {
          id?: string;
          module_id?: string | null;
          title?: string;
          method?: string;
          endpoint?: string;
          description?: string | null;
          auth_requirement?: string;
          tags?: string[] | null;
          notes?: string | null;
          version?: string | null;
          deprecated?: boolean;
          sort_order?: number;
          visibility?: boolean;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
}